[package]
name = "AoC2015"
version = "0.21.0"
edition = "2021"
description = "Solving the Advent of Code 2015"

[dependencies]
digest = "~0.10.0"
md-5 = "~0.10.0"
serde =  {version = "^1.0.0", features = ["derive"]}
serde_json = "^1.0.0"
itertools = "^0.10.0"
